export const POSTS: { title: string; href: string; description: string }[] = [
  {
    title: "Tech In tDot",
    href: "/blog/tech-in-tdot",
    description: "All the cool tech related things in Toronto",
  },
  {
    title: "Next.js (React)",
    href: "/blog/next-js",
    description: "Sharing my notes while I'm learning new things.",
  },
  {
    title: "JavaScript",
    href: "/blog/javascript",
    description: "Random stuff about me.",
  },
  {
    title: "DSA",
    href: "/blog/data-structures-and-algorithms",
    description: "Random stuff about me.",
  },
  {
    title: "System Design",
    href: "/blog/system-design",
    description: "Random stuff about me.",
  },
  {
    title: "DevOps",
    href: "/blog/system-design",
    description: "Random stuff about me.",
  },
  {
    title: "Notes",
    href: "/blog/js-notes",
    description: "Random stuff about me.",
  },
  // {
  //   title: "Performance",
  //   href: "/blog/performance",
  //   description: "How to make your next app Blazing fast",
  // },
  // {
  //   title: "Animaion",
  //   href: "/blog/animations",
  //   description:
  //     "Everything you need to know about animations. We are going to learn about animation library like framer motion, GSAP and many more.",
  // },
  // {
  //   title: "Career",
  //   href: "/blog/career",
  //   description:
  //     "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
  // },
];

export const projectCategories: {
  title: string;
  href: string;
  description: string;
}[] = [
  {
    title: "Enterprise-Grade Web Applications",
    href: "/projects/next-js",
    description:
      "Scalable business solutions to enhance performance and operations.",
  },
  {
    title: "Data Structures and Algorithms",
    href: "/projects/dsa",
    description: "Implementations of data structures and algorithms.",
  },
  {
    title: "Games",
    href: "/projects/games",
    description:
      "Interactive games demonstrating OOP and problem-solving skills.",
  },
  {
    title: "DevOps - Cloud Solutions",
    href: "/projects/devops",
    description:
      "Automated infrastructure to streamline deployment and reliability.",
  },
  {
    title: "E-Commerce Platforms",
    href: "/projects/ecommerce",
    description: "Custom online stores focused on scalability and performance.",
  },
  {
    title: "API Development",
    href: "/projects/apis",
    description:
      "Robust, scalable APIs for data integration and communication.",
  },
];

export const keywords = [
  "Santhosh",
  "Santhosh Bhoopal",
  "Web Development",
  "Web Development Mississauga",
  "Web Development Toronto",
  "Web Developer",
  "Web Developer Mississauga",
  "Web Developer Toronto",
  "Software Engineer",
  "Software Developer",
  "Full stack developer",
  "Full stack developer Mississauga",
  "Full stack developer Toronto",
  "Frontend developer",
  "Backend developer",
  "Toronto",
  "Near me",
  "Mississauga",
  "Web Design",
  "Web Design Mississauga",
  "Web Design Toronto",
  "Web Designer",
  "Web Designer Mississauga",
  "Web Designer Toronto",
  "Web Development Services",
  "Web Development Services Mississauga",
  "Web Development Services Toronto",
  "Web Development Company",
  "Web Development Company Mississauga",
  "Web Development Company Toronto",
  "Web Development Agency",
  "Web Development Agency Mississauga",
  "Web Development Agency Toronto",
  "Web Development Firm",
  "Web Development Firm Mississauga",
  "Web Development Firm Toronto",
  "Web Development Studio",
  "Web Development Studio Mississauga",
  "Web Development Studio Toronto",
  "Next.js",
  "React",
  "JavaScript",
  "Data Structures and Algorithms",
  "System Design",
  "DevOps",
  "Tech in tDot",
  "TorontoJS",
  "TechTankTO",
  "Tech in Toronto",
  "Blog",
  "Self taught developer",
  "Frontend development",
  "Backend development",
  "Full stack development",
  "HTML5",
  "CSS3",
  "JavaScript frameworks",
  "React.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "REST API",
  "GraphQL",
  "Web hosting",
  "Responsive design",
  "UI/UX design",
  "Web accessibility",
  "Version control (Git)",
  "Content Management Systems (CMS)",
  "WordPress development",
  "eCommerce platforms",
  "PHP development",
  "Ruby on Rails",
  "ASP.NET",
  "Progressive Web Apps (PWAs)",
  "Web performance optimization (WPO)",
  "Mobile-first design",
  "Web security (HTTPS, SSL)",
  "SEO best practices",
  "Agile development",
  "Scrum",
  "Continuous integration/continuous deployment (CI/CD)",
  "WebSockets",
  "Webpack",
  "Database management (SQL, NoSQL)",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Docker",
  "Cloud platforms (AWS, Azure, Google Cloud)",

  // NLP Keywords
  "Build modern web applications",
  "Responsive website design",
  "Optimize for mobile devices",
  "Single-page application (SPA)",
  "Cross-browser compatibility",
  "Backend logic implementation",
  "Frontend user interface",
  "Client-server architecture",
  "Third-party integrations",
  "API development",
  "Server-side rendering (SSR)",
  "Component-based architecture",
  "Web application frameworks",
  "DevOps for web development",
  "Version control systems",
  "Containerized development",
  "Cloud-native applications",
  "Interactive web elements",
  "Custom web components",
  "Design patterns for web",
  "Web analytics integration",
  "User authentication and authorization",
  "Scalability in web applications",
  "Asynchronous JavaScript (AJAX)",
  "Static site generation",
  "Data-driven web applications",
  "Real-time web applications",
  "SaaS product development",
  "Headless CMS",
  "Accessibility standards compliance",
  "Page load speed optimization",
  "Web development lifecycle",
  "User experience (UX) optimization",
  "Custom web solutions",
  "Dynamic web content",

  // Combined LSI + NLP Keywords
  "Custom responsive web design",
  "Modern JavaScript frameworks",
  "Server-side API development",
  "Progressive enhancement strategies",
  "Full-stack web application",
  "Cloud-hosted web services",
  "Database-driven websites",
  "User authentication systems",
  "Front-end framework optimization",
  "Real-time data syncing",
  "Web performance tuning",
  "API integration and testing",
  "Web app security and encryption",
  "Mobile-first web development",
  "Continuous integration pipelines",
  "Headless CMS architecture",
  "SEO-friendly website structure",
  "Agile web development methodologies",
  "How to build responsive websites with React",
  "Best practices for optimizing web performance",
  "Full-stack development with Node.js and MongoDB",
  "Creating an SEO-friendly website structure",
  "How to integrate third-party APIs into web apps",
  "Optimizing JavaScript frameworks for faster loading",
  "Best frameworks for building single-page applications",
  "How to secure a web application with HTTPS and SSL",
  "Developing mobile-first websites using CSS3",
  "Deploying web applications on AWS and Azure",
  "Setting up continuous integration pipelines for web development",
  "How to build real-time web applications using WebSockets",
  "A complete guide to version control with Git for developers",
  "How to use Docker for web development environments",
  "Using progressive enhancement strategies in web design",
  "Best practices for UI/UX design in web development",
  "How to create dynamic web content with server-side rendering",
  "A guide to optimizing web applications for mobile devices",
  "Choosing the right CMS for a scalable web project",
  "How to implement authentication in web apps with JWT",

  // Natural Mentions
  "What are the latest trends in frontend web development?",
  "Is full-stack development a good career path?",
  "How do you implement user authentication in a web app?",
  "What's the difference between REST API and GraphQL?",
  "How can I improve the performance of my web application?",
  "What is server-side rendering, and when should I use it?",
  "Why is mobile-first design important for web development?",
  "How do you optimize images for faster page load times?",
  "What tools are best for version control in web development?",
  "What are the benefits of using containerization with Docker?",
  "How do you integrate Google Analytics into a website?",
  "What are the most popular web frameworks in 2024?",
  "What are the key principles of modern UI/UX design?",
  "What is the role of cloud hosting in web development?",
  "How do I deploy a website using Vercel or Netlify?",
  "What are the best practices for optimizing SEO on a website?",
  "How do you build a secure web application?",
  "Why is accessibility important in web design?",
  "What is the difference between frontend and backend development?",
  "How do you use version control in a team development environment?",
  "Web design services in Mississauga",
  "Custom web development Mississauga",
  "Mississauga web developers",
  "Frontend and backend development Mississauga",
  "E-commerce website design Mississauga",
  "Responsive websites in Mississauga",
  "Digital marketing and web development Mississauga",
  "Website maintenance services Mississauga",
  "SEO web development Mississauga",
  "WordPress development Mississauga",
  "Web app development Mississauga",
  "Mississauga website design company",
  "Mobile-friendly websites Mississauga",
  "Website redesign services Mississauga",
  "UI/UX design Mississauga",
  "PHP web development Mississauga",
  "Web development agencies in Mississauga",
  "Cloud hosting services in Mississauga",
  "Full-stack developers Mississauga",
  "Mississauga digital solutions",

  // NLP Keywords
  "Affordable web development in Mississauga",
  "Top-rated web development agencies in Mississauga",
  "Where to find web developers in Mississauga",
  "How to hire a web developer in Mississauga",
  "Mississauga web design for small businesses",
  "Best web development companies in Mississauga",
  "Local web development services in Mississauga",
  "Mississauga’s leading web development team",
  "Custom website solutions for Mississauga businesses",
  "How to build a website in Mississauga",
  "Web design and development packages Mississauga",
  "Professional web development for Mississauga startups",
  "Full-service web development in Mississauga",
  "SEO-optimized web design Mississauga",
  "Custom web applications for Mississauga clients",
  "Mississauga website hosting and management",
  "Mobile app and web development Mississauga",
  "Mississauga’s digital experts in web development",
  "Building scalable websites for Mississauga companies",
  "How Mississauga businesses benefit from web development",
  "Affordable custom web development services in Mississauga",
  "Best web development companies for small businesses in Mississauga",
  "Full-stack web development services in Mississauga for startups",
  "How to hire a professional web developer in Mississauga",
  "Mobile-friendly website design services in Mississauga",
  "Best web design and SEO companies in Mississauga",
  "How to redesign a website for Mississauga businesses",
  "E-commerce website development solutions in Mississauga",
  "Top-rated web development agencies in Mississauga for SEO",
  "Mississauga cloud hosting and web management services",
  "Responsive web design services in Mississauga for local businesses",
  "How to integrate SEO with web design in Mississauga",
  "Custom web application development in Mississauga",
  "Local web development packages for businesses in Mississauga",
  "Website maintenance and optimization services in Mississauga",

  // Natural Mentions
  "Where can I find affordable web development in Mississauga?",
  "Who are the top web developers in Mississauga?",
  "How much does it cost to build a website in Mississauga?",
  "What are the best web design companies in Mississauga?",
  "Is there a reliable web development agency in Mississauga?",
  "Can I get SEO services along with web design in Mississauga?",
  "What are the benefits of hiring a web developer in Mississauga?",
  "How do I choose the right web development company in Mississauga?",
  "How long does it take to develop a website in Mississauga?",
  "What is the process of creating an e-commerce site in Mississauga?",
  "Can I get mobile app development with web development in Mississauga?",
  "What is the best platform for web development in Mississauga?",
  "Do Mississauga web developers offer website redesign services?",
  "How do I improve my website’s SEO with a Mississauga agency?",
  "How do I maintain my website after development in Mississauga?",

  // LSI Keywords
  "Full stack web developer in Mississauga",
  "Toronto-based web design expert",
  "Custom web development services by Santhosh Bhoopal",
  "Mississauga full stack developer for hire",
  "Frontend and backend development by Santhosh Bhoopal",
  "E-commerce website design by Santhosh Bhoopal",
  "Full stack development in Toronto and Mississauga",
  "Web development services by Santhosh Bhoopal",
  "Responsive website design Mississauga",
  "UI/UX design and web development Toronto",
  "Professional website solutions in Mississauga",
  "Santhosh Bhoopal – custom web applications",
  "Full stack solutions for small businesses in Toronto",
  "Digital marketing and web development expert Mississauga",
  "Mississauga web development by Santhosh Bhoopal",
  "Secure website development Toronto",
  "Freelance full stack developer in Toronto",
  "Web app development Mississauga",
  "Local website maintenance services in Toronto",
  "Full stack consulting in Mississauga and Toronto",

  // NLP Keywords
  "Affordable web development by Santhosh Bhoopal in Mississauga",
  "Hire a full stack developer in Mississauga or Toronto",
  "Professional website design services by Santhosh Bhoopal",
  "How to get custom web development with Santhosh Bhoopal",
  "Best full stack developer in Mississauga and Toronto",
  "Full stack web developer specializing in UI/UX design",
  "Custom e-commerce solutions by Santhosh Bhoopal",
  "Web development for startups by Santhosh Bhoopal",
  "Mississauga web design expert Santhosh Bhoopal",
  "Freelance web developer in Toronto specializing in custom solutions",
  "Full stack development projects by Santhosh Bhoopal",
  "How to contact Santhosh Bhoopal for web design services",
  "Full stack developer with expertise in digital marketing",
  "Web design services for small businesses by Santhosh Bhoopal",
  "Santhosh Bhoopal – your go-to web development expert in Toronto",
  "How to create responsive websites with Santhosh Bhoopal",
  "Full stack web development portfolio of Santhosh Bhoopal",
  "Best practices in web design by Santhosh Bhoopal",
  "Full stack developer offering website maintenance services",
  "Secure and optimized websites by Santhosh Bhoopal in Mississauga",
  "Affordable custom web development services by Santhosh Bhoopal in Mississauga",
  "Best full stack developer in Toronto specializing in e-commerce",
  "Professional web design services for small businesses in Mississauga",
  "Full stack web development solutions for startups in Toronto",
  "How to hire a freelance web developer in Mississauga",
  "Responsive website design and development by Santhosh Bhoopal",
  "Custom web applications for local businesses in Mississauga",
  "Web development and SEO services by Santhosh Bhoopal in Toronto",
  "Freelance full stack developer available for projects in Mississauga",
  "UI/UX design and web development packages in Toronto",
  "Top-rated web design services by Santhosh Bhoopal in Mississauga",
  "E-commerce website development solutions for Toronto startups",
  "Mississauga web design expert offering affordable solutions",
  "How to get custom web design services in Toronto",
  "Santhosh Bhoopal's portfolio of web development projects in Mississauga",

  // Natural Mentions
  "Where can I find a reliable full stack developer in Mississauga?",
  "What services does Santhosh Bhoopal offer as a web developer?",
  "How much does it cost to hire a web developer in Toronto?",
  "Can Santhosh Bhoopal help with e-commerce website design?",
  "What are the benefits of hiring a freelance web developer in Mississauga?",
  "How do I contact Santhosh Bhoopal for web design services?",
  "What types of web applications can Santhosh Bhoopal develop?",
  "Is Santhosh Bhoopal experienced in responsive web design?",
  "How to choose the right web developer in Toronto?",
  "Can I get SEO services included with my web development project?",
  "How does Santhosh Bhoopal approach web development projects?",
  "What is the process for creating a website with Santhosh Bhoopal?",
  "Does Santhosh Bhoopal offer website maintenance services?",
  "How can I improve my website's user experience with Santhosh Bhoopal?",
  "What are the latest trends in web design that Santhosh Bhoopal follows?",
];
